import { Toaster } from "@/components/ui/primitives/toaster";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "PomoSuperFocus",
    template: "%s | PomoSuperFocus",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </StoreProvider>
    </html>
  );
}
